-- Public, read-only pot sharing.
--
-- A pot owner/admin can switch on a share link. Anyone holding the link can
-- read a SANITIZED snapshot of that one pot without an account and without
-- becoming a member. Nothing here widens RLS on any existing table: anonymous
-- callers still cannot read pots, pot_members, transactions, users or anything
-- else directly. The only way in is the `get_public_pot(token)` RPC below.
--
-- Security model
-- --------------
-- * Sharing is OFF for every existing pot. A pot is shared only after an
--   owner/admin calls `enable_pot_public_share`.
-- * The public identifier is a random token (~244 bits, URL-safe base64), not
--   the pot id. It is generated by the database from `gen_random_uuid()` (a
--   CSPRNG), so it cannot be guessed or derived from any id.
-- * `pot_public_share` has RLS enabled with NO policies and every API-role
--   privilege revoked. It is reachable only through the SECURITY DEFINER
--   functions in this file, each of which re-checks authorization.
-- * Turning sharing off sets `is_enabled = false` / `revoked_at` in the same
--   statement the caller commits, so the link stops working immediately. The
--   revoked row is kept (audit trail) and its token never works again; turning
--   sharing back on issues a NEW token.
-- * `get_public_pot` is the only anon-callable function. It looks up exactly one
--   token, validates its format, enabled state and pot, and returns a JSON
--   document built from an allow-list of fields. It returns NO ids of any kind
--   (pot, member, transaction, user, category, ...) to non-members.
--
-- Deliberately NOT exposed publicly: emails, phone numbers, auth/user ids, any
-- internal id, join/invite codes, member roles and access levels, transaction
-- notes (free text that may be private), payment methods and pool accounts,
-- pool transfers (internal bookkeeping), planned payments / vendor commitments,
-- join requests, notifications, and other pots.

-- ---------------------------------------------------------------------------
-- Table
-- ---------------------------------------------------------------------------
create table public.pot_public_share (
  id uuid primary key default gen_random_uuid(),
  pot_id uuid not null references public.pots(id) on delete cascade,
  public_token text not null,
  is_enabled boolean not null default true,
  -- Nullable + SET NULL so deleting an account never blocks on old share rows.
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  constraint pot_public_share_token_format
    check (public_token ~ '^[A-Za-z0-9_-]{32,128}$'),
  constraint pot_public_share_revoked_consistent
    check ((is_enabled and revoked_at is null) or (not is_enabled and revoked_at is not null))
);

-- Token lookup (the hot path for every public view) + global uniqueness.
create unique index pot_public_share_token_key
  on public.pot_public_share (public_token);

-- At most one live link per pot; revoked rows accumulate as history.
create unique index pot_public_share_one_active_per_pot
  on public.pot_public_share (pot_id)
  where is_enabled;

create index pot_public_share_pot_idx
  on public.pot_public_share (pot_id);

comment on table public.pot_public_share is
  'Public read-only share links, one live row per pot. Access only via get_public_pot / *_pot_public_share RPCs.';
comment on column public.pot_public_share.public_token is
  'Random URL-safe token shown in /pot/<token>. Never the pot id.';

-- RLS on with no policies = deny by default, even if a grant slips in later.
alter table public.pot_public_share enable row level security;

-- Supabase grants new public tables to anon/authenticated by default; take that
-- back. Reads and writes go through the SECURITY DEFINER RPCs only.
revoke all on table public.pot_public_share from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Token generation (internal; not callable through the API)
-- ---------------------------------------------------------------------------
-- 32 bytes built from two random UUIDs (122 random bits each) -> 43 chars of
-- URL-safe base64 without padding.
create or replace function public.generate_public_share_token()
returns text
language sql
volatile
set search_path = public
as $$
  select translate(
    rtrim(
      encode(
        decode(replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''), 'hex'),
        'base64'
      ),
      '='
    ),
    '+/',
    '-_'
  );
$$;

revoke all on function public.generate_public_share_token() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Manage sharing (authenticated pot members)
-- ---------------------------------------------------------------------------

-- Current share state for the pot's Share sheet. Any active member can see the
-- link once it is enabled (so they can pass it on); only owners/admins can
-- change it (`can_manage`). `token` is null while sharing is off.
create or replace function public.get_pot_public_share(p_pot_id uuid)
returns table (
  enabled boolean,
  token text,
  shared_at timestamptz,
  can_manage boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_share public.pot_public_share;
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;
  if not public.is_pot_member(p_pot_id) then
    raise exception 'not a member of this pot';
  end if;

  select * into v_share
    from public.pot_public_share s
    where s.pot_id = p_pot_id and s.is_enabled;

  if found then
    return query select true, v_share.public_token, v_share.created_at, public.is_pot_admin(p_pot_id);
  else
    return query select false, null::text, null::timestamptz, public.is_pot_admin(p_pot_id);
  end if;
end;
$$;

-- Turn sharing on. Idempotent: if a live link already exists it is returned
-- unchanged (the token is NOT rotated). Owner/admin only.
create or replace function public.enable_pot_public_share(p_pot_id uuid)
returns table (
  enabled boolean,
  token text,
  shared_at timestamptz,
  can_manage boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_share public.pot_public_share;
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;
  if not public.is_pot_admin(p_pot_id) then
    raise exception 'only a pot admin can change public sharing';
  end if;

  -- Serialise concurrent enables/disables for this pot.
  perform 1 from public.pots p where p.id = p_pot_id for update;

  select * into v_share
    from public.pot_public_share s
    where s.pot_id = p_pot_id and s.is_enabled;

  if not found then
    insert into public.pot_public_share (pot_id, public_token, created_by)
    values (p_pot_id, public.generate_public_share_token(), auth.uid())
    returning * into v_share;
  end if;

  return query select true, v_share.public_token, v_share.created_at, true;
end;
$$;

-- Turn sharing off. The live link dies as soon as this commits. Idempotent.
-- Owner/admin only.
create or replace function public.disable_pot_public_share(p_pot_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;
  if not public.is_pot_admin(p_pot_id) then
    raise exception 'only a pot admin can change public sharing';
  end if;

  perform 1 from public.pots p where p.id = p_pot_id for update;

  update public.pot_public_share s
    set is_enabled = false,
        revoked_at = now()
    where s.pot_id = p_pot_id and s.is_enabled;
end;
$$;

-- ---------------------------------------------------------------------------
-- Public read (anonymous + authenticated)
-- ---------------------------------------------------------------------------
-- Returns one of:
--   {"status":"not_found"}   unknown / malformed token
--   {"status":"revoked"}     the link existed but sharing was turned off
--   {"status":"ok", ...}     sanitized pot snapshot (see below)
--
-- Money is integer paise, like everywhere else. Pool balance follows the same
-- rule as the apps: contributions minus pool expenses. Totals cover the whole
-- ledger; the transaction list is capped at 500 rows (newest first) so an
-- anonymous caller cannot force an unbounded payload.
create or replace function public.get_public_pot(p_token text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  c_tx_limit constant int := 500;
  v_share public.pot_public_share;
  v_pot public.pots;
  v_contributed bigint;
  v_spent bigint;
  v_pool_spent bigint;
  v_tx_count bigint;
  v_member_count bigint;
  v_members jsonb;
  v_transactions jsonb;
  v_viewer_pot_id uuid;
begin
  -- Reject junk before touching the table.
  if p_token is null or p_token !~ '^[A-Za-z0-9_-]{32,128}$' then
    return jsonb_build_object('status', 'not_found');
  end if;

  select * into v_share
    from public.pot_public_share s
    where s.public_token = p_token;
  if not found then
    return jsonb_build_object('status', 'not_found');
  end if;
  if not v_share.is_enabled then
    return jsonb_build_object('status', 'revoked');
  end if;

  select * into v_pot from public.pots p where p.id = v_share.pot_id;
  if not found then
    return jsonb_build_object('status', 'not_found');
  end if;

  -- Ledger totals. Pool transfers move money between pool accounts and never
  -- change what the group contributed, spent or holds, so they are ignored.
  select
    coalesce(sum(t.amount) filter (where t.type = 'contribution'), 0),
    coalesce(sum(t.amount) filter (where t.type in ('pool_expense', 'member_expense')), 0),
    coalesce(sum(t.amount) filter (where t.type = 'pool_expense'), 0),
    count(*)
  into v_contributed, v_spent, v_pool_spent, v_tx_count
  from public.transactions t
  where t.pot_id = v_pot.id
    and t.type <> 'pool_transfer';

  -- Active members: display name + what they put in. No ids, roles or contact info.
  select
    count(*),
    coalesce(
      jsonb_agg(
        jsonb_build_object('name', m.display_name, 'contributed', coalesce(c.total, 0))
        order by m.created_at, m.display_name
      ),
      '[]'::jsonb
    )
  into v_member_count, v_members
  from public.pot_members m
  left join lateral (
    select sum(t.amount) as total
    from public.transactions t
    where t.pot_id = m.pot_id
      and t.type = 'contribution'
      and t.paid_by = m.id
  ) c on true
  where m.pot_id = v_pot.id
    and m.status = 'active';

  -- Ledger rows, newest first. Every member/category lookup is pinned to this
  -- pot, and people appear by display name only. `note` is intentionally left out.
  select coalesce(jsonb_agg(x.j order by x.date desc, x.created_at desc, x.id), '[]'::jsonb)
  into v_transactions
  from (
    select
      t.id,
      t.date,
      t.created_at,
      jsonb_build_object(
        'type', t.type,
        'description', t.description,
        'amount', t.amount,
        'date', t.date,
        'created_at', t.created_at,
        'paid_by', pb.display_name,
        'to', tm.display_name,
        'category', case
          when cat.id is null then null
          else jsonb_build_object('name', cat.name, 'icon', cat.icon, 'color', cat.color)
        end,
        'participants', case
          when t.type in ('pool_expense', 'member_expense') then (
            select coalesce(jsonb_agg(pm.display_name order by pm.display_name), '[]'::jsonb)
            from public.pot_members pm
            where pm.pot_id = t.pot_id
              and pm.id = any (coalesce(t.participants, '{}'::uuid[]))
          )
          else '[]'::jsonb
        end
      ) as j
    from public.transactions t
    left join public.pot_members pb on pb.id = t.paid_by and pb.pot_id = t.pot_id
    left join public.pot_members tm on tm.id = t.to_member and tm.pot_id = t.pot_id
    left join public.pot_categories cat on cat.id = t.category_id and cat.pot_id = t.pot_id
    where t.pot_id = v_pot.id
      and t.type <> 'pool_transfer'
    order by t.date desc, t.created_at desc, t.id
    limit c_tx_limit
  ) x;

  -- Signed-in members get a pointer to the normal app experience. The id is
  -- only ever returned to someone who is already an active member of this pot.
  if auth.uid() is not null and public.is_pot_member(v_pot.id) then
    v_viewer_pot_id := v_pot.id;
  end if;

  return jsonb_build_object(
    'status', 'ok',
    'pot', jsonb_build_object(
      'name', v_pot.name,
      'description', v_pot.description,
      'currency', v_pot.currency,
      'archived', v_pot.status = 'archived'
    ),
    'summary', jsonb_build_object(
      'member_count', v_member_count,
      'contributed', v_contributed,
      'spent', v_spent,
      'balance', v_contributed - v_pool_spent,
      'transaction_count', v_tx_count
    ),
    'members', v_members,
    'transactions', v_transactions,
    'transactions_truncated', v_tx_count > c_tx_limit,
    'viewer_pot_id', v_viewer_pot_id,
    'generated_at', now()
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Grants. Supabase's default privileges hand new functions to anon, so every
-- function that must NOT be anonymous is revoked from anon explicitly.
-- ---------------------------------------------------------------------------
revoke all on function public.get_pot_public_share(uuid) from public, anon;
revoke all on function public.enable_pot_public_share(uuid) from public, anon;
revoke all on function public.disable_pot_public_share(uuid) from public, anon;
grant execute on function public.get_pot_public_share(uuid) to authenticated;
grant execute on function public.enable_pot_public_share(uuid) to authenticated;
grant execute on function public.disable_pot_public_share(uuid) to authenticated;

revoke all on function public.get_public_pot(text) from public;
grant execute on function public.get_public_pot(text) to anon, authenticated;
